"""Strict runtime contracts for the HIWM inference and lock record.

The models intentionally contain no example dialogue, candidate action, or
probability.  Runtime values must come from the current observation and the
configured OpenAI-compatible model.
"""

from __future__ import annotations

import re
from typing import Annotated, Any, Dict, List, Literal, Optional

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    ValidationInfo,
    field_validator,
    model_validator,
)


SCHEMA_VERSION = "1.0"
Probability = Annotated[float, Field(ge=0.0, le=1.0)]


# This is deliberately a claim boundary, not a sentiment classifier. It is
# applied only to text generated by the world model; user observations remain
# available for self-report and evidence grounding. Patterns name classes of
# prohibited inferences, while _SAFE_CLAIM_FRAME recognizes explicit refusal,
# insufficient-evidence, and risk-warning language about those classes.
_PROHIBITED_CLAIM_PATTERNS: tuple[tuple[str, re.Pattern[str]], ...] = (
    (
        "hidden_emotion_or_inner_state",
        re.compile(
            r"真实情绪|隐藏情绪|内心(?:状态|想法|感受)|真实感受|读心|"
            r"(?:用户|对方|此人|这个人|他|她)(?:目前|现在|显然|其实|内心)?"
            r"(?:很|非常|感到|是)?(?:愤怒|生气|紧张|焦虑|高兴|悲伤|害怕|恐惧)|"
            r"\b(?:true|hidden|underlying)\s+emotions?\b|"
            r"\binner\s+(?:state|thoughts?|feelings?)\b|"
            r"\bmind[- ]?reading\b|\bread\s+(?:the\s+|their\s+|his\s+|her\s+)?mind\b|"
            r"\b(?:the\s+)?(?:user|person|they|he|she)\s+"
            r"(?:is|seems|feels)\s+(?:angry|nervous|anxious|happy|sad|afraid)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "personality_or_essential_trait",
        re.compile(
            r"人格(?:本质|特征|类型|障碍)?|性格(?:本质|特征|类型)?|"
            r"\bpersonality(?:\s+(?:trait|type|disorder))?\b|"
            r"\bcharacter\s+traits?\b|\b(?:introvert|extrovert)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "deception",
        re.compile(
            r"撒谎|说谎|欺骗|测谎|谎言|不诚实|"
            r"\b(?:lying|liar|lies|deceive|deceives|deceived|deceiving|"
            r"deceptive|deception|dishonest|lie detector)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "diagnosis_or_health_status",
        re.compile(
            r"(?:心理|精神|医学)诊断|(?:心理|精神)疾病|精神病|"
            r"抑郁症|焦虑症|躁郁症|双相情感障碍|自闭症|人格障碍|"
            r"患有(?:抑郁|焦虑|躁郁|双相|自闭|精神疾病|心理疾病)|"
            r"\bdiagnos(?:e|ed|es|ing|is)\b|\bmental\s+illness\b|"
            r"\b(?:depressive|anxiety|bipolar|autism|personality)\s+disorder\b|"
            r"\b(?:has|have|suffers?\s+from)\s+"
            r"(?:depression|anxiety|bipolar disorder|autism)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "protected_or_sensitive_trait",
        re.compile(
            r"种族|族裔|民族(?:身份|背景)?|宗教(?:信仰)?|"
            r"政治(?:立场|倾向|观点|身份|归属)?|性取向|残障|残疾|"
            r"(?:生理|社会)?性别|年龄|怀孕|国籍|公民身份|婚姻状况|"
            r"同性恋|异性恋|双性恋|跨性别|穆斯林|基督徒|佛教徒|"
            r"\b(?:race|racial|ethnicity|ethnic|religion|religious affiliation|"
            r"political (?:affiliation|beliefs?|views?)|sexual orientation|"
            r"disability|disabled|gender identity|pregnan(?:t|cy)|nationality|"
            r"citizenship|marital status|age|gay|lesbian|bisexual|transgender|"
            r"muslim|christian|jewish|buddhist)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "high_impact_employment_decision",
        re.compile(
            r"(?:适合|应该|应当|建议|可以|不适合|不应该).{0,10}"
            r"(?:招聘|录用|晋升|升职|解雇|开除|裁员|裁掉)|"
            r"(?:招聘|录用|晋升|升职|解雇|开除|裁员)(?:决定|建议|资格|适格|人选)|"
            r"适合被裁|该裁(?:掉|员)|"
            r"\b(?:should|suitable|fit|eligible|recommend(?:ed)?)\b.{0,48}"
            r"\b(?:hire|hired|hiring|fire|fired|firing|promote|promoted|promotion|"
            r"lay\s*off|laid\s*off|layoff|termination)\b|"
            r"\b(?:hiring|firing|promotion|termination|layoff)\s+"
            r"(?:decision|recommendation|suitability|eligibility)\b|"
            r"(?:招聘|录用|晋升|升职|解雇|开除|裁掉)(?:这个|该|那名)?"
            r"(?:员工|候选人|求职者|此人)|"
            r"\b(?:hire|fire|promote|lay\s*off)\s+(?:the|this|that)\s+"
            r"(?:employee|candidate|person)\b",
            re.IGNORECASE,
        ),
    ),
    (
        "loyalty_moral_worth_or_dangerousness",
        re.compile(
            r"忠诚度|是否忠诚|(?:用户|对方|此人|他|她)(?:很|非常|不|是)?忠诚|"
            r"道德价值|道德品质|人品|危险人物|具有危险性|犯罪倾向|"
            r"\b(?:loyalty|moral worth|moral character|dangerousness|"
            r"dangerous person|criminal tendency)\b|"
            r"\b(?:the\s+)?(?:user|person|they|he|she)\s+"
            r"(?:is|seems)\s+(?:not\s+)?(?:loyal|dangerous)\b",
            re.IGNORECASE,
        ),
    ),
)

_CLAUSE_SPLIT = re.compile(
    r"(?:[。！？；;.!?]+|\n+|\b(?:but|however|yet|instead|therefore|so)\b|"
    r"\band\s+(?=(?:the\s+)?(?:user|person|they|he|she)\b)|"
    r"[,，]\s*(?=(?:the\s+)?(?:user|person|they|he|she)\b|"
    r"(?:用户|对方|此人|这个人|他|她))|"
    r"但是|但|然而|不过|而是|却|因此|所以|"
    r"(?:并且|同时)(?=(?:用户|对方|此人|这个人|他|她)))",
    re.IGNORECASE,
)
_SAFE_CLAIM_FRAME = re.compile(
    r"不能|无法|不可|不应|不应该|不得|禁止|避免|拒绝|不要|不作|不做|不适合|"
    r"不推断|不判断|不确定|无法确认|没有(?:足够)?(?:证据|依据)|"
    r"缺乏(?:证据|依据)|不代表|并不(?:能|表示|意味着)|不是|没有|"
    r"风险(?:是|在于|来自)?|可能误判|防止误判|"
    r"\b(?:cannot|can't|can not|must not|mustn't|should not|shouldn't|"
    r"do not|don't|never|avoid|refuse to|insufficient evidence|"
    r"not enough evidence|does not (?:show|mean|indicate|prove)|"
    r"not (?:appropriate|permitted|supported|possible|suitable|fit|eligible)|"
    r"(?:is|are|was|were|does|do|did) not|risk(?: of| is)?|"
    r"guardrail|warning)\b",
    re.IGNORECASE,
)
_SAFE_CLAIM_AFTER = re.compile(
    r"^(?:.{0,24})?(?:不能|无法|不应|不应该|不可|不得|缺乏证据|"
    r"cannot|can't|can not|should not|must not|is not supported|"
    r"cannot be|can't be)",
    re.IGNORECASE,
)


def _safe_generated_text(value: str, field_name: str) -> str:
    """Reject prohibited model-generated claims without inspecting user text."""

    text = value.strip()
    if not text:
        raise ValueError(f"{field_name} must not be blank")
    for clause in _CLAUSE_SPLIT.split(text):
        if not clause.strip():
            continue
        for category, pattern in _PROHIBITED_CLAIM_PATTERNS:
            for match in pattern.finditer(clause):
                prefix = clause[max(0, match.start() - 96) : match.start()]
                suffix = clause[match.end() : match.end() + 48]
                framing_window = prefix + match.group(0)
                if _SAFE_CLAIM_FRAME.search(framing_window) or _SAFE_CLAIM_AFTER.search(
                    suffix
                ):
                    continue
                raise ValueError(
                    f"{field_name} contains prohibited model-generated claim class: "
                    f"{category}"
                )
    return text


class StrictContract(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True)


class EvidenceReference(StrictContract):
    evidence_id: str = Field(min_length=1)
    modality: Literal["asr", "camera", "history"]
    source: str = Field(min_length=1)
    observed_at: float = Field(ge=0.0)
    stream_key: Optional[str] = None
    content: Optional[str] = None
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    metadata: Dict[str, Any] = Field(default_factory=dict)

    @field_validator("evidence_id", "source")
    @classmethod
    def _strip_required_text(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("value must not be blank")
        return value


class ObservationSnapshot(StrictContract):
    cutoff_at: float = Field(ge=0.0)
    current_asr: EvidenceReference
    camera: Optional[EvidenceReference] = None
    history: List[EvidenceReference] = Field(default_factory=list)

    @model_validator(mode="after")
    def _validate_modalities_and_ids(self) -> "ObservationSnapshot":
        if self.current_asr.modality != "asr":
            raise ValueError("current_asr must have modality='asr'")
        if not self.current_asr.content or not self.current_asr.content.strip():
            raise ValueError("current_asr must contain finalized text")
        if self.camera is not None and self.camera.modality != "camera":
            raise ValueError("camera must have modality='camera'")
        if any(item.modality != "history" for item in self.history):
            raise ValueError("history entries must have modality='history'")
        if any(not item.content or not item.content.strip() for item in self.history):
            raise ValueError("history entries must contain text")
        ids = [self.current_asr.evidence_id]
        if self.camera is not None:
            ids.append(self.camera.evidence_id)
        ids.extend(item.evidence_id for item in self.history)
        if len(ids) != len(set(ids)):
            raise ValueError("evidence_id values must be unique within an observation")
        return self

    def evidence_ids(self) -> set[str]:
        ids = {self.current_asr.evidence_id}
        if self.camera is not None:
            ids.add(self.camera.evidence_id)
        ids.update(item.evidence_id for item in self.history)
        return ids


class BeliefItem(StrictContract):
    id: str = Field(min_length=1)
    statement: str = Field(min_length=1)
    status: Literal["known", "working_hypothesis", "unknown"]
    confidence: Probability
    evidence_refs: List[str] = Field(min_length=1)
    change: Literal["new", "updated", "unchanged", "retracted"]

    @field_validator("id")
    @classmethod
    def _strip_belief_id(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("belief id must not be blank")
        return value

    @field_validator("statement")
    @classmethod
    def _validate_belief_statement(cls, value: str, info: ValidationInfo) -> str:
        return _safe_generated_text(value, info.field_name)

    @field_validator("evidence_refs")
    @classmethod
    def _unique_evidence_refs(cls, value: List[str]) -> List[str]:
        if any(not item.strip() for item in value):
            raise ValueError("evidence_refs must not contain blank IDs")
        if len(value) != len(set(value)):
            raise ValueError("evidence_refs must be unique")
        return value


class BeliefState(StrictContract):
    items: List[BeliefItem] = Field(min_length=1, max_length=24)

    @model_validator(mode="after")
    def _unique_belief_ids(self) -> "BeliefState":
        ids = [item.id for item in self.items]
        if len(ids) != len(set(ids)):
            raise ValueError("belief_id values must be unique")
        return self


class ContentSignal(StrictContract):
    """A task-relevant statement grounded in observable conversation content."""

    id: str = Field(min_length=1)
    category: Literal["need", "concern", "commitment", "question", "unknown"]
    statement: str = Field(min_length=1)
    confidence: Probability
    evidence_refs: List[str] = Field(min_length=1)
    change: Literal["new", "updated", "unchanged", "retracted"]

    @field_validator("id")
    @classmethod
    def _strip_content_id(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("content signal id must not be blank")
        return value

    @field_validator("statement")
    @classmethod
    def _validate_content_statement(cls, value: str, info: ValidationInfo) -> str:
        return _safe_generated_text(value, info.field_name)

    @field_validator("evidence_refs")
    @classmethod
    def _unique_content_evidence_refs(cls, value: List[str]) -> List[str]:
        if any(not item.strip() for item in value):
            raise ValueError("evidence_refs must not contain blank IDs")
        if len(value) != len(set(value)):
            raise ValueError("evidence_refs must be unique")
        return value


class StateDelta(StrictContract):
    target: str = Field(min_length=1)
    predicted_change: str = Field(min_length=1)

    @field_validator("target", "predicted_change")
    @classmethod
    def _validate_delta_text(cls, value: str, info: ValidationInfo) -> str:
        return _safe_generated_text(value, info.field_name)


class CandidateAction(StrictContract):
    action_id: str = Field(min_length=1)
    strategy: str = Field(min_length=1)
    utterance: str = Field(min_length=1)
    predicted_observation: str = Field(min_length=1)
    predicted_state_delta: List[StateDelta] = Field(min_length=1)
    goal_probability: Probability
    risk_probability: Probability
    risk: str = Field(min_length=1)
    uncertainty: Probability
    information_gain: Probability = 0.0
    evidence_refs: List[str] = Field(min_length=1)

    @field_validator("action_id")
    @classmethod
    def _strip_action_id(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("action id must not be blank")
        return value

    @field_validator("strategy", "utterance", "predicted_observation", "risk")
    @classmethod
    def _validate_action_text(cls, value: str, info: ValidationInfo) -> str:
        return _safe_generated_text(value, info.field_name)

    @field_validator("evidence_refs")
    @classmethod
    def _validate_action_refs(cls, value: List[str]) -> List[str]:
        if any(not item.strip() for item in value):
            raise ValueError("evidence_refs must not contain blank IDs")
        if len(value) != len(set(value)):
            raise ValueError("evidence_refs must be unique")
        return value


class PreviousTurnFeedback(StrictContract):
    previous_turn_id: str = Field(min_length=1)
    actual_observation: str = Field(min_length=1)
    comparison: Literal["matched", "partial", "miss", "indeterminate"]
    explanation: str = Field(min_length=1)
    evidence_refs: List[str] = Field(min_length=1)

    @field_validator("previous_turn_id", "actual_observation")
    @classmethod
    def _strip_feedback_text(cls, value: str) -> str:
        value = value.strip()
        if not value:
            raise ValueError("feedback text must not be blank")
        return value

    @field_validator("explanation")
    @classmethod
    def _validate_feedback_explanation(cls, value: str, info: ValidationInfo) -> str:
        # actual_observation is intentionally excluded: it may contain a user's
        # self-report. Only the model-authored comparison explanation is gated.
        return _safe_generated_text(value, info.field_name)

    @field_validator("evidence_refs")
    @classmethod
    def _validate_feedback_refs(cls, value: List[str]) -> List[str]:
        if any(not item.strip() for item in value):
            raise ValueError("evidence_refs must not contain blank IDs")
        if len(value) != len(set(value)):
            raise ValueError("evidence_refs must be unique")
        return value


class HIWMModelInference(StrictContract):
    content_signals: List[ContentSignal] = Field(min_length=1, max_length=20)
    beliefs: List[BeliefItem] = Field(min_length=1, max_length=24)
    actions: List[CandidateAction] = Field(min_length=3, max_length=3)
    feedback: Optional[PreviousTurnFeedback] = None

    @model_validator(mode="after")
    def _validate_distinct_actions(self) -> "HIWMModelInference":
        content_ids = [item.id for item in self.content_signals]
        if len(content_ids) != len(set(content_ids)):
            raise ValueError("content signal id values must be unique")
        belief_ids = [item.id for item in self.beliefs]
        if len(belief_ids) != len(set(belief_ids)):
            raise ValueError("belief id values must be unique")
        action_ids = [item.action_id for item in self.actions]
        strategies = [item.strategy.casefold() for item in self.actions]
        utterances = [item.utterance.casefold() for item in self.actions]
        if len(set(action_ids)) != 3:
            raise ValueError("the three action_id values must be unique")
        if len(set(strategies)) != 3:
            raise ValueError("the three action strategies must be materially distinct")
        if len(set(utterances)) != 3:
            raise ValueError("the three action utterances must be distinct")
        return self

    def validate_against_observation(
        self,
        observation: ObservationSnapshot,
        previous_turn_id: Optional[str],
    ) -> None:
        """Reject invented evidence IDs and inconsistent feedback linkage."""

        allowed = observation.evidence_ids()
        current_asr_id = observation.current_asr.evidence_id
        for signal in self.content_signals:
            unknown = set(signal.evidence_refs) - allowed
            if unknown:
                raise ValueError(
                    f"content signal {signal.id!r} references unknown evidence: {sorted(unknown)}"
                )
            if current_asr_id not in signal.evidence_refs:
                raise ValueError(
                    f"content signal {signal.id!r} must reference the finalized current ASR evidence"
                )
        for belief in self.beliefs:
            unknown = set(belief.evidence_refs) - allowed
            if unknown:
                raise ValueError(
                    f"belief {belief.id!r} references unknown evidence: {sorted(unknown)}"
                )
        for action in self.actions:
            unknown = set(action.evidence_refs) - allowed
            if unknown:
                raise ValueError(
                    f"action {action.action_id!r} references unknown evidence: {sorted(unknown)}"
                )
            if current_asr_id not in action.evidence_refs:
                raise ValueError(
                    f"action {action.action_id!r} must reference the finalized current ASR evidence"
                )

        if previous_turn_id is None:
            if self.feedback is not None:
                raise ValueError(
                    "feedback must be null when there is no previous locked turn"
                )
            return
        if self.feedback is None:
            raise ValueError(
                "feedback is required when a previous locked turn is supplied"
            )
        if self.feedback.previous_turn_id != previous_turn_id:
            raise ValueError(
                "feedback.previous_turn_id does not match the supplied locked turn"
            )
        unknown = set(self.feedback.evidence_refs) - allowed
        if unknown:
            raise ValueError(f"feedback references unknown evidence: {sorted(unknown)}")
        if current_asr_id not in self.feedback.evidence_refs:
            raise ValueError(
                "feedback must reference the finalized current ASR evidence"
            )


class PlannerWeights(StrictContract):
    goal: float = Field(default=1.0, ge=0.0)
    risk: float = Field(default=1.0, ge=0.0)
    uncertainty: float = Field(default=0.5, ge=0.0)
    information_gain: float = Field(default=0.35, ge=0.0)

    @model_validator(mode="after")
    def _at_least_one_weight(self) -> "PlannerWeights":
        if (
            self.goal == 0
            and self.risk == 0
            and self.uncertainty == 0
            and self.information_gain == 0
        ):
            raise ValueError("at least one planner weight must be positive")
        return self


class PlannerSafetyPolicy(StrictContract):
    """Hard exit thresholds applied independently of the model's ranking."""

    min_goal_probability: Probability = 0.30
    max_risk_probability: Probability = 0.70
    max_uncertainty: Probability = 0.75


class ActionScore(StrictContract):
    action_id: str
    score: float
    goal_component: float
    risk_component: float
    uncertainty_component: float
    information_gain_component: float = 0.0


class PlannerDecision(StrictContract):
    formula: Literal[
        "goal-risk-uncertainty-v1",
        "goal-information-gain-risk-uncertainty-v2",
    ] = "goal-risk-uncertainty-v1"
    weights: PlannerWeights
    scores: List[ActionScore] = Field(min_length=3, max_length=3)
    selected_action_id: str = Field(min_length=1)


class ModelInfo(StrictContract):
    provider: Literal["openai_compatible"] = "openai_compatible"
    model_name: str = Field(min_length=1)
    api_url: str = Field(min_length=1)
    response_id: Optional[str] = None
    requested_at: float = Field(ge=0.0)
    completed_at: float = Field(ge=0.0)
    probability_kind: Literal["uncalibrated_model_estimate"] = (
        "uncalibrated_model_estimate"
    )

    @model_validator(mode="after")
    def _validate_timing(self) -> "ModelInfo":
        if self.completed_at < self.requested_at:
            raise ValueError("completed_at cannot precede requested_at")
        return self


class PredictionPayload(StrictContract):
    schema_version: Literal["1.0"] = SCHEMA_VERSION
    session_id: str = Field(min_length=1)
    turn_id: str = Field(min_length=1)
    objective: str = Field(min_length=1)
    observation: ObservationSnapshot
    content_signals: List[ContentSignal] = Field(min_length=1, max_length=20)
    beliefs: List[BeliefItem] = Field(min_length=1, max_length=24)
    actions: List[CandidateAction] = Field(min_length=3, max_length=3)
    selected_action_id: str = Field(min_length=1)
    planner: PlannerDecision
    feedback: Optional[PreviousTurnFeedback] = None
    model: ModelInfo
    locked_at: float = Field(ge=0.0)

    @model_validator(mode="after")
    def _selected_action_exists(self) -> "PredictionPayload":
        content_ids = [item.id for item in self.content_signals]
        if len(content_ids) != len(set(content_ids)):
            raise ValueError("content signal id values must be unique")
        belief_ids = [item.id for item in self.beliefs]
        if len(belief_ids) != len(set(belief_ids)):
            raise ValueError("belief id values must be unique")
        action_id_list = [item.action_id for item in self.actions]
        if len(action_id_list) != len(set(action_id_list)):
            raise ValueError("action_id values must be unique")
        action_ids = set(action_id_list)
        if self.selected_action_id not in action_ids:
            raise ValueError("selected_action_id is not present in actions")
        if self.planner.selected_action_id != self.selected_action_id:
            raise ValueError("planner selection and selected_action_id disagree")
        return self


class LockProof(StrictContract):
    algorithm: Literal["sha256"] = "sha256"
    prediction_id: str = Field(min_length=1)
    action_id: str = Field(min_length=1)
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    locked_at: float = Field(ge=0.0)


class LockedPredictionRecord(PredictionPayload):
    locked_prediction: LockProof


class HIWMError(StrictContract):
    schema_version: Literal["1.0"] = SCHEMA_VERSION
    session_id: str = Field(min_length=1)
    turn_id: str = Field(min_length=1)
    stage: Literal[
        "input_validation", "api", "response_validation", "planner", "ledger", "output"
    ]
    code: str = Field(min_length=1)
    message: str = Field(min_length=1)
    occurred_at: float = Field(ge=0.0)


class SafetyFallbackPayload(StrictContract):
    """A locked safe response used when prediction is explicitly unavailable."""

    schema_version: Literal["1.0"] = SCHEMA_VERSION
    session_id: str = Field(min_length=1)
    turn_id: str = Field(min_length=1)
    stage: Literal[
        "input_validation", "api", "response_validation", "planner", "ledger", "output"
    ]
    action_id: Literal["clarify", "wait"]
    utterance: str = Field(min_length=1)
    probability_kind: Literal["unavailable"] = "unavailable"
    reason: str = Field(min_length=1)
    locked_at: float = Field(ge=0.0)


class LockedSafetyFallbackRecord(SafetyFallbackPayload):
    locked_prediction: LockProof
